version: "3.9"
services:
  realsense_ros2:
    image: my_ssl_slam  # Change to the tag you built
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /home/emkk/Downloads:/root/Downloads:rw
